# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
use_frameworks!
inhibit_all_warnings!
target 'tvMed' do
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'SVProgressHUD'
pod 'Fabric'
pod 'Crashlytics'
end

target 'tvMedTests' do

end

target 'tvMedUITests' do

end

